{% set name = "diffsims" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee1d3ed510f16b6fc4e14573b828c7970c614696d124e93ea9950f6a1c010a3f

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - scipy >=0.15
    - numpy >=1.17
    - matplotlib-base >=3.1.1
    - tqdm >=4.9
    - transforms3d
    - diffpy.structure >=3.0.0
    - orix >=0.9.0
    - psutil
    - numba

test:
  requires:
    - pytest
  imports:
    - diffsims
    - diffsims.utils
    - diffsims.generators
    - diffsims.sims
    - diffsims.libraries
  commands:
    - pytest --pyargs diffsims

about:
  home: https://github.com/pyxem/diffsims
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for diffraction simulations
  doc_url: www.pyxem.org

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
    - hakonanes
