{% set name = "diffsims" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce0db1bcda5614b40c3faf27f17581d35c2745dc093d4ee21c773fe48efea1df

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - scipy >=1.0
    - numpy >=1.17
    - matplotlib-base >=3.3
    - tqdm >=4.9
    - transforms3d
    - diffpy.structure >=3.0.0
    - orix >=0.9.0
    - psutil
    - numba

test:
  requires:
    - pip
    - pytest
  imports:
    - diffsims
    - diffsims.crystallography
    - diffsims.generators
    - diffsims.libraries
    - diffsims.sims
    - diffsims.utils
  commands:
    - pip check
    - export MPLBACKEND=agg  # [unix]
    - set MPLBACKEND=agg  # [win]
    - pytest --pyargs diffsims

about:
  home: https://diffsims.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for diffraction simulations
  dev_url: https://github.com/pyxem/diffsims
  doc_url: https://diffsims.readthedocs.io/en/stable

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
    - hakonanes
