{% set name = "diffsims" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dc8cbb6aa5f4a6f0c40cc2c52d33dd486136227c328714b6635db7746f1729a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - diffpy.structure >=3.0.2
    - matplotlib-base >=3.3
    - python >=3.8
    - numba
    - numpy >=1.17.3
    - orix-base
    - psutil
    - scipy >=1.8
    - tqdm >=4.9
    - transforms3d

test:
  requires:
    - pip
    - pytest
  imports:
    - diffsims
    - diffsims.crystallography
    - diffsims.generators
    - diffsims.libraries
    - diffsims.pattern
    - diffsims.sims
    - diffsims.simulations
    - diffsims.structure_factor
    - diffsims.utils
  commands:
    - pip check
    - export MPLBACKEND=agg  # [unix]
    - set MPLBACKEND=agg  # [win]
    - pytest --pyargs diffsims -k "not test_same_simulation_results"

about:
  home: https://diffsims.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for diffraction simulations
  dev_url: https://github.com/pyxem/diffsims
  doc_url: https://diffsims.readthedocs.io/en/stable

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
    - hakonanes
    - CSSFrancis
