travis:
  secure:
    BINSTAR_TOKEN: LzwpKNfhFJuvDQ5jZ1QyW5DUrnvT3XrDTmCSG2+rhAJzpEi58DC3IvXIQjwTNow19h93H908U9nF/IHzzdv9JBuRk13TjRBUEFumwzBhG4lR1YyjlAH3VOPozplVQZY9UepmukW3tD1VvPFF0Xk/++nCT8eGNFKiXnJViCCtSivRITRIfkq4umimVOB9l7UMp7aizMeFTda0Kbuas8inB5KDDHpgBAzX31qoTVHWZEZvMpGuSxbfEWMpuZxycmH+WqbwgZPM0I1X0sgwbi2zJrsm9ubleYcElY0AlxuxN/Te+eNoHFJHd4jXM+MKgHyG5uWELEkzRGsDrHmeSyzBhdw2kS7sSb9KYpIiROLyHwYcLmDdsaWHTPXk2/RO8eSOnwC/zHprUfZ+w63OeWVZblGKA70H927n3SNxU3hNYrhH0D0i7A/bcOGYcyRHUWiELw1ApNSJX8HiICpAB9hys/m/nuqA0goSW+A0laU+wWMLpqaIA20QoXdzB6UJBgPergQ/Xl90BE9ODhOOG6KW+DYSnMrz7HDNrExllscZpEkIaRXSMDoCyGcehL0t/a7nimOcSnvmFaR3YPPEFOguC1hE924e50HWxBOOHt15py3s8vXBVLEdEUaAHZ5l2Ta1gW5BnKebEbvOpwYLa0DDKT263wlvC18lBIlbcdVjT8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
